### get all todos
get http://localhost:3000/api/todos

### get todo by id
get http://localhost:3000/api/todos/1

### sign up
post http://localhost:3000/signup
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}

### sign in
post http://localhost:3000/signin
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}